
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install flake8
  - pip install coverage
  - pip install mypy
  - pip install pycontracts
script:
  - python -m doctest python_lab_2.py
  - flake8 python_lab_2.py
  - flake8 --max-complexity=2
  - python python_lab_2.py -m coverage --with-coverage --cover-min-percentage=99
  - mypy --ignore-missing-imports python_lab_2.py
