
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install flake8
  #- pip install autopep8

# command to run tests
script:
  - flake8 python_lab_2.py
  - python3 -m doctest python_lab_2.py
  - flake8 --max-complexity=2

#- autopep8 python_lab_2.py
